// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gmsg.proto

#ifndef PROTOBUF_gmsg_2eproto__INCLUDED
#define PROTOBUF_gmsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace gproto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_gmsg_2eproto();
void protobuf_AssignDesc_gmsg_2eproto();
void protobuf_ShutdownFile_gmsg_2eproto();

class MSG_C2G_HeartBeat;
class MSG_G2C_HeartBeat;
class MSG_C2G_StartGame;

// ===================================================================

class MSG_C2G_HeartBeat : public ::google::protobuf::Message {
 public:
  MSG_C2G_HeartBeat();
  virtual ~MSG_C2G_HeartBeat();

  MSG_C2G_HeartBeat(const MSG_C2G_HeartBeat& from);

  inline MSG_C2G_HeartBeat& operator=(const MSG_C2G_HeartBeat& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_C2G_HeartBeat& default_instance();

  void Swap(MSG_C2G_HeartBeat* other);

  // implements Message ----------------------------------------------

  MSG_C2G_HeartBeat* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSG_C2G_HeartBeat& from);
  void MergeFrom(const MSG_C2G_HeartBeat& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:gproto.MSG_C2G_HeartBeat)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_gmsg_2eproto();
  friend void protobuf_AssignDesc_gmsg_2eproto();
  friend void protobuf_ShutdownFile_gmsg_2eproto();

  void InitAsDefaultInstance();
  static MSG_C2G_HeartBeat* default_instance_;
};
// -------------------------------------------------------------------

class MSG_G2C_HeartBeat : public ::google::protobuf::Message {
 public:
  MSG_G2C_HeartBeat();
  virtual ~MSG_G2C_HeartBeat();

  MSG_G2C_HeartBeat(const MSG_G2C_HeartBeat& from);

  inline MSG_G2C_HeartBeat& operator=(const MSG_G2C_HeartBeat& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_G2C_HeartBeat& default_instance();

  void Swap(MSG_G2C_HeartBeat* other);

  // implements Message ----------------------------------------------

  MSG_G2C_HeartBeat* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSG_G2C_HeartBeat& from);
  void MergeFrom(const MSG_G2C_HeartBeat& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:gproto.MSG_G2C_HeartBeat)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_gmsg_2eproto();
  friend void protobuf_AssignDesc_gmsg_2eproto();
  friend void protobuf_ShutdownFile_gmsg_2eproto();

  void InitAsDefaultInstance();
  static MSG_G2C_HeartBeat* default_instance_;
};
// -------------------------------------------------------------------

class MSG_C2G_StartGame : public ::google::protobuf::Message {
 public:
  MSG_C2G_StartGame();
  virtual ~MSG_C2G_StartGame();

  MSG_C2G_StartGame(const MSG_C2G_StartGame& from);

  inline MSG_C2G_StartGame& operator=(const MSG_C2G_StartGame& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_C2G_StartGame& default_instance();

  void Swap(MSG_C2G_StartGame* other);

  // implements Message ----------------------------------------------

  MSG_C2G_StartGame* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSG_C2G_StartGame& from);
  void MergeFrom(const MSG_C2G_StartGame& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes rolename = 1;
  inline bool has_rolename() const;
  inline void clear_rolename();
  static const int kRolenameFieldNumber = 1;
  inline const ::std::string& rolename() const;
  inline void set_rolename(const ::std::string& value);
  inline void set_rolename(const char* value);
  inline void set_rolename(const void* value, size_t size);
  inline ::std::string* mutable_rolename();
  inline ::std::string* release_rolename();
  inline void set_allocated_rolename(::std::string* rolename);

  // @@protoc_insertion_point(class_scope:gproto.MSG_C2G_StartGame)
 private:
  inline void set_has_rolename();
  inline void clear_has_rolename();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* rolename_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_gmsg_2eproto();
  friend void protobuf_AssignDesc_gmsg_2eproto();
  friend void protobuf_ShutdownFile_gmsg_2eproto();

  void InitAsDefaultInstance();
  static MSG_C2G_StartGame* default_instance_;
};
// ===================================================================


// ===================================================================

// MSG_C2G_HeartBeat

// -------------------------------------------------------------------

// MSG_G2C_HeartBeat

// -------------------------------------------------------------------

// MSG_C2G_StartGame

// required bytes rolename = 1;
inline bool MSG_C2G_StartGame::has_rolename() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MSG_C2G_StartGame::set_has_rolename() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MSG_C2G_StartGame::clear_has_rolename() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MSG_C2G_StartGame::clear_rolename() {
  if (rolename_ != &::google::protobuf::internal::kEmptyString) {
    rolename_->clear();
  }
  clear_has_rolename();
}
inline const ::std::string& MSG_C2G_StartGame::rolename() const {
  return *rolename_;
}
inline void MSG_C2G_StartGame::set_rolename(const ::std::string& value) {
  set_has_rolename();
  if (rolename_ == &::google::protobuf::internal::kEmptyString) {
    rolename_ = new ::std::string;
  }
  rolename_->assign(value);
}
inline void MSG_C2G_StartGame::set_rolename(const char* value) {
  set_has_rolename();
  if (rolename_ == &::google::protobuf::internal::kEmptyString) {
    rolename_ = new ::std::string;
  }
  rolename_->assign(value);
}
inline void MSG_C2G_StartGame::set_rolename(const void* value, size_t size) {
  set_has_rolename();
  if (rolename_ == &::google::protobuf::internal::kEmptyString) {
    rolename_ = new ::std::string;
  }
  rolename_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MSG_C2G_StartGame::mutable_rolename() {
  set_has_rolename();
  if (rolename_ == &::google::protobuf::internal::kEmptyString) {
    rolename_ = new ::std::string;
  }
  return rolename_;
}
inline ::std::string* MSG_C2G_StartGame::release_rolename() {
  clear_has_rolename();
  if (rolename_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = rolename_;
    rolename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void MSG_C2G_StartGame::set_allocated_rolename(::std::string* rolename) {
  if (rolename_ != &::google::protobuf::internal::kEmptyString) {
    delete rolename_;
  }
  if (rolename) {
    set_has_rolename();
    rolename_ = rolename;
  } else {
    clear_has_rolename();
    rolename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace gproto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_gmsg_2eproto__INCLUDED
