// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gpid.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "gpid.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace gproto {

namespace {

const ::google::protobuf::EnumDescriptor* PID_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_gpid_2eproto() {
  protobuf_AddDesc_gpid_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "gpid.proto");
  GOOGLE_CHECK(file != NULL);
  PID_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_gpid_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_gpid_2eproto() {
}

void protobuf_AddDesc_gpid_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\ngpid.proto\022\006gproto*\372\004\n\003PID\022\027\n\022CSID_C2G"
    "_HeartBeat\020\220N\022\027\n\022CSID_G2C_HeartBeat\020\221N\022\027"
    "\n\022CSID_C2G_StartGame\020\364N\022\025\n\020CSID_C2G_Prep"
    "are\020\330O\022\025\n\020CSID_G2C_Prepare\020\331O\022\034\n\026CSID_G2"
    "C_PrepareGround\020\204\235\001\022\032\n\024CSID_C2G_EnterGro"
    "und\020\205\235\001\022\032\n\024CSID_G2C_EnterGround\020\206\235\001\022\032\n\024C"
    "SID_C2G_LeaveGround\020\207\235\001\022\032\n\024CSID_G2C_Leav"
    "eGround\020\210\235\001\022\034\n\026CSID_C2G_GetGroundInfo\020\216\235"
    "\001\022\034\n\026CSID_G2C_GetGroundInfo\020\217\235\001\022!\n\033CSID_"
    "G2C_GObjectEnterGround\020\230\235\001\022\034\n\026CSID_G2C_B"
    "attlePrepare\020\231\235\001\022\032\n\024CSID_G2C_BattleStart"
    "\020\232\235\001\022\033\n\025CSID_G2C_BattleReward\020\233\235\001\022\034\n\026CSI"
    "D_C2G_PrepareFinish\020\242\235\001\022\032\n\024CSID_G2C_Batt"
    "leFight\020\254\235\001\022\035\n\027CSID_C2G_BattleFightEnd\020\255"
    "\235\001\022\030\n\022CSID_C2G_MoveFight\020\266\235\001\022\030\n\022CSID_G2C"
    "_MoveFight\020\267\235\001\022\023\n\rCSID_G2C_Move\020\270\235\001\022\024\n\016C"
    "SID_G2C_Fight\020\271\235\001", 657);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "gpid.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_gpid_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_gpid_2eproto {
  StaticDescriptorInitializer_gpid_2eproto() {
    protobuf_AddDesc_gpid_2eproto();
  }
} static_descriptor_initializer_gpid_2eproto_;
const ::google::protobuf::EnumDescriptor* PID_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PID_descriptor_;
}
bool PID_IsValid(int value) {
  switch(value) {
    case 10000:
    case 10001:
    case 10100:
    case 10200:
    case 10201:
    case 20100:
    case 20101:
    case 20102:
    case 20103:
    case 20104:
    case 20110:
    case 20111:
    case 20120:
    case 20121:
    case 20122:
    case 20123:
    case 20130:
    case 20140:
    case 20141:
    case 20150:
    case 20151:
    case 20152:
    case 20153:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace gproto

// @@protoc_insertion_point(global_scope)
